# Generated by Django 4.0 on 2021-12-13 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newmodel',
            name='test',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
