# Generated by Django 4.0 on 2021-12-15 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0002_newmodel_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newmodel',
            name='test',
        ),
    ]
